# Generated by Django 3.2.9 on 2021-11-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('businessID', models.IntegerField(primary_key=True, serialize=False)),
                ('businessName', models.CharField(max_length=64)),
                ('organisationType', models.CharField(choices=[('SP', 'SoleProprietor'), ('P', 'Partnership'), ('PL', 'PrivateLimited'), ('PBL', 'PublicLimited')], max_length=3)),
                ('businessType', models.CharField(max_length=64)),
                ('currency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyID', models.IntegerField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=64)),
                ('companyEmail', models.EmailField(max_length=254)),
                ('companyPhoneNumber', models.IntegerField()),
                ('is_client', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsAndServices',
            fields=[
                ('itemID', models.IntegerField(primary_key=True, serialize=False)),
                ('isProduct', models.BooleanField()),
                ('itemDescription', models.CharField(max_length=500)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('billID', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('NA', 'NotApproved')], max_length=2)),
                ('businessID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.business')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.productsandservices')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('salesID', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('NA', 'NotApproved')], max_length=2)),
                ('businessID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.business')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.productsandservices')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=64)),
                ('accessLevel', models.CharField(choices=[('0', 'Admin'), ('1', 'Business'), ('2', 'CompanyUser')], max_length=1)),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('billID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.purchases')),
                ('salesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.sales')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('S', 'Sales'), ('P', 'Purchases')], max_length=1)),
                ('businessID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.business')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.users')),
            ],
        ),
    ]
