# Generated by Django 3.2.9 on 2021-11-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_productsandservices_psname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.CharField(max_length=64),
        ),
    ]
