# Generated by Django 3.2.9 on 2021-11-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_business_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.CharField(choices=[('PKR', 'Pakistani Ruppee'), ('USD', 'United States Dollar'), ('EUR', 'Euro'), ('AED', 'Dirham'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], max_length=3),
        ),
    ]
