# Generated by Django 3.2.9 on 2021-11-28 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_purchases_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_sale',
            fields=[
                ('itemsaleID', models.AutoField(primary_key=True, serialize=False)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.productsandservices')),
                ('salesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.sales')),
            ],
        ),
    ]
