# Generated by Django 3.2.9 on 2021-12-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20211130_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=64),
        ),
    ]
